### PR TITLE
(#174) Add kqueue backend for FMW

### PR DESCRIPTION
**Pull request by zhiayang**
This should work on both macos and BSD.

### CODE REVIEW

**Comment by herrhotzenplotz** [comment]
Compiles on FreeBSD.
@zhiayang You didn't remove the TODO in the code for #174

**Comment by zhiayang** [comment]
doesn't snitch remove todos that are closed?

**Comment by herrhotzenplotz** [comment]
yeah, but a manual purge is required

**Comment by rexim** [comment]
@zhiayang @herrhotzenplotz looks good to me! :+1: Thank you so much for your contribution!

**Pull request merged**
